
import React, { useState, useRef } from 'react';
import { createPortal } from 'react-dom';
import { Monitor, Smartphone, Settings, Check, Loader2, FileCode, X, AlertCircle, Copy } from 'lucide-react';
import { DocumentDesign, ServiceProvider } from '../types';
import { OpenAIConfig } from '../services/openaiService';
import { streamWeChatArticleFromMarkdown, ExportAIConfig } from '../services/wechatExportService';
import { useToast } from './ToastSystem';

interface ExportToolbarProps {
  designData: DocumentDesign;
  previewMode: 'desktop' | 'mobile';
  setPreviewMode: (mode: 'desktop' | 'mobile') => void;
  t: any;
  markdownContent: string;
  provider: ServiceProvider;
  openaiConfig: OpenAIConfig;
}

export const ExportToolbar: React.FC<ExportToolbarProps> = ({
  designData,
  previewMode,
  setPreviewMode,
  t,
  markdownContent,
  provider,
  openaiConfig
}) => {
  const [copiedType, setCopiedType] = useState<'config' | 'html' | null>(null);
  const [isExporting, setIsExporting] = useState(false);
  const { addToast } = useToast();
  
  // Preview State for Streaming
  const [showPreview, setShowPreview] = useState(false);
  const [currentCardIndex, setCurrentCardIndex] = useState<number | null>(null);
  const [totalCards, setTotalCards] = useState<number>(0);
  const [currentCardHtml, setCurrentCardHtml] = useState<string>('');
  const [completedCards, setCompletedCards] = useState<number[]>([]);
  const [exportError, setExportError] = useState<string | null>(null);
  
  // Store final result for manual copying if auto-copy fails (focus lost)
  const [generatedHtml, setGeneratedHtml] = useState<string | null>(null);

  const handleCopyLayout = () => {
    const jsonString = JSON.stringify(designData, null, 2);
    navigator.clipboard.writeText(jsonString).then(() => {
      setCopiedType('config');
      addToast(t.copied, 'success');
      setTimeout(() => setCopiedType(null), 2000);
    });
  };

  const performCopy = async (htmlContent: string) => {
    const wrappedHtml = `
<div class="rich_media_content js_underline_content autoTypeSetting24psection fix_apple_default_style" id="js_content" style="text-size-adjust: inherit; visibility: visible;">
  ${htmlContent}
  <section style="text-align: center; margin-top: 40px; font-size: 12px; color: #999; opacity: 0.5;">
     Generated by LayoutForge AI
  </section>
</div>
    `;

    try {
      const htmlBlob = new Blob([wrappedHtml], { type: 'text/html' });
      const textBlob = new Blob([markdownContent], { type: 'text/plain' });

      await navigator.clipboard.write([
          new ClipboardItem({
          'text/html': htmlBlob,
          'text/plain': textBlob,
          }),
      ]);
      
      setCopiedType('html');
      addToast(t.copied + " (WeChat HTML)", 'success');
      setTimeout(() => setCopiedType(null), 2500);
      return true;
    } catch (err) {
        console.warn("Clipboard API failed, trying fallback execCommand:", err);
        
        // Fallback for environments where Clipboard API is blocked or permission denied
        try {
           const tempDiv = document.createElement('div');
           // Make it invisible but part of layout so it can be selected.
           // Note: display:none doesn't work for selection, so we use fixed off-screen.
           tempDiv.style.cssText = 'position:fixed; left:-9999px; top:0; z-index:-1; opacity:0; pointer-events:none; white-space: pre-wrap;';
           tempDiv.innerHTML = wrappedHtml;
           document.body.appendChild(tempDiv);
           
           const range = document.createRange();
           range.selectNode(tempDiv);
           
           const selection = window.getSelection();
           if (selection) {
               selection.removeAllRanges();
               selection.addRange(range);
               const success = document.execCommand('copy');
               selection.removeAllRanges();
               document.body.removeChild(tempDiv);
               
               if (success) {
                   setCopiedType('html');
                   addToast(t.copied + " (WeChat HTML)", 'success');
                   setTimeout(() => setCopiedType(null), 2500);
                   return true;
               }
           }
        } catch (fallbackErr) {
           console.error("Fallback copy failed:", fallbackErr);
           addToast("Copy failed. Please copy manually.", 'error');
        }
        return false;
    }
  };

  const handleCopyWeChat = async () => {
    // 1. Validation
    if (provider === 'openai' && !openaiConfig.apiKey) {
        addToast('Please configure OpenAI API Key in AI settings.', 'error');
        return;
    }
    
    // Check for Gemini Key presence (process.env.API_KEY is injected by Vite)
    if (provider === 'gemini' && !process.env.API_KEY) {
        addToast('Gemini API Key is missing in environment variables.', 'error');
        return;
    }

    // 2. Prepare Config
    const exportConfig: ExportAIConfig = {
        provider,
        openai: provider === 'openai' ? openaiConfig : undefined,
        geminiApiKey: provider === 'gemini' ? process.env.API_KEY : undefined
    };

    // 3. Start Export Process
    setIsExporting(true);
    setShowPreview(true);
    setExportError(null);
    setGeneratedHtml(null); // Reset
    setCurrentCardIndex(0); // Set initial 0 to show UI immediately
    setTotalCards(0);
    setCompletedCards([]);
    setCurrentCardHtml('');

    try {
      const highlightColor = designData.highlightColor || 'rgb(121, 115, 247)';

      const fullHtml = await streamWeChatArticleFromMarkdown(
        exportConfig,
        markdownContent,
        highlightColor,
        (index, total) => {
          setTotalCards(total);
          setCurrentCardIndex(index);
          setCurrentCardHtml('');
        },
        (index, partialHtml) => {
          setCurrentCardIndex(index);
          setCurrentCardHtml(partialHtml);
        },
        (index, fullCardHtml) => {
          setCompletedCards(prev => [...prev, index]);
        }
      );

      setGeneratedHtml(fullHtml);
      
      // Attempt Auto-Copy
      const success = await performCopy(fullHtml);
      if (!success) {
          addToast("Auto-copy blocked by browser. Please click the copy button below.", 'info');
      }

    } catch (error: any) {
      console.error("Export failed", error);
      setExportError(error.message || "Failed to generate layout.");
      addToast(error.message || "Export failed", 'error');
    } finally {
      setIsExporting(false);
    }
  };

  const closePreview = () => {
      setShowPreview(false);
      setExportError(null);
      setGeneratedHtml(null);
  };

  return (
    <>
      <div className="h-14 border-b border-slate-200/50 flex items-center justify-between px-6 bg-white/80 backdrop-blur-sm sticky top-0 z-10 shadow-sm">
        <div className="flex items-center gap-2">
          <span className="text-xs font-bold text-slate-500 uppercase tracking-wider">{t.livePreview}</span>
        </div>
        
        <div className="flex items-center gap-2">
          {/* Device Toggle */}
          <div className="flex bg-slate-100 p-1 rounded-lg border border-slate-200 mr-2">
            <button 
              onClick={() => setPreviewMode('desktop')}
              className={`p-1.5 rounded-md transition-all ${previewMode === 'desktop' ? 'bg-white shadow-sm text-indigo-600' : 'text-slate-400 hover:text-slate-600'}`}
              title={t.desktop}
            >
              <Monitor className="w-4 h-4" />
            </button>
            <button 
              onClick={() => setPreviewMode('mobile')}
              className={`p-1.5 rounded-md transition-all ${previewMode === 'mobile' ? 'bg-white shadow-sm text-indigo-600' : 'text-slate-400 hover:text-slate-600'}`}
              title={t.mobile}
            >
              <Smartphone className="w-4 h-4" />
            </button>
          </div>

          {/* Copy Config Button */}
          <button 
            onClick={handleCopyLayout}
            className="flex items-center gap-2 px-3 py-2 bg-white border border-slate-200 hover:bg-slate-50 text-slate-700 text-xs font-medium rounded-lg transition shadow-sm"
            title={t.copyConfig}
          >
            {copiedType === 'config' ? <Check className="w-3.5 h-3.5" /> : <Settings className="w-3.5 h-3.5" />}
            <span className="hidden sm:inline">{copiedType === 'config' ? t.copied : 'Config'}</span>
          </button>

          {/* Copy HTML Button */}
          <button 
            onClick={handleCopyWeChat}
            disabled={isExporting}
            className={`flex items-center gap-2 px-3 py-2 text-white text-xs font-medium rounded-lg transition shadow-sm overflow-hidden relative ${isExporting ? 'bg-slate-700 cursor-wait' : 'bg-slate-900 hover:bg-slate-800'}`}
            title="Export for WeChat (AI Generated)"
          >
            <div className="relative flex items-center gap-2 z-10">
                {isExporting ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : 
                copiedType === 'html' ? <Check className="w-3.5 h-3.5" /> : <FileCode className="w-3.5 h-3.5" />}
                <span className="hidden sm:inline">
                    {isExporting ? 'Generating...' : (copiedType === 'html' ? t.copied : t.copyHtml)}
                </span>
            </div>
          </button>
        </div>
      </div>

      {/* Floating Preview Window - Rendered in Body via Portal */}
      {showPreview && createPortal(
        <div className="fixed bottom-4 right-4 w-[420px] max-h-[70vh] bg-slate-900 text-slate-100 rounded-xl shadow-2xl border border-slate-700 flex flex-col z-[100] animate-in slide-in-from-bottom-4 fade-in font-sans">
          
          {/* Header */}
          <div className="flex items-center justify-between px-3 py-3 border-b border-slate-700 bg-slate-800/50 rounded-t-xl">
             <div className="flex items-center gap-2">
                {exportError ? <AlertCircle className="w-4 h-4 text-red-500" /> : <Loader2 className={`w-4 h-4 ${isExporting ? 'animate-spin text-indigo-400' : 'text-emerald-400'}`} />}
                <span className="text-sm font-medium">
                  {exportError ? 'Export Error' : (generatedHtml ? 'Generation Complete' : `Generating... ${totalCards > 0 ? `(${ (currentCardIndex || 0) + 1}/${totalCards})` : ''}`)}
                </span>
             </div>
             <button 
               onClick={closePreview} 
               className="text-slate-400 hover:text-white transition p-1.5 hover:bg-slate-700 rounded-lg"
             >
               <X className="w-4 h-4" />
             </button>
          </div>

          {/* Code Preview Area */}
          <div className="flex-1 overflow-auto p-4 bg-black/30 min-h-[200px] scrollbar-thin scrollbar-thumb-slate-700">
            {exportError ? (
               <div className="text-red-300 text-sm p-3 bg-red-950/30 rounded border border-red-900/50 leading-relaxed">
                 {exportError}
                 <div className="mt-2 text-xs opacity-70">
                    If this persists, check your API key in settings.
                 </div>
               </div>
            ) : (
                <pre className="text-[11px] leading-relaxed whitespace-pre-wrap break-all font-mono text-emerald-400/90 font-light">
                {currentCardHtml || (generatedHtml ? '// Ready to copy' : '// Waiting for stream...')}
                </pre>
            )}
          </div>
          
          {/* Footer / Progress Bar / Actions */}
          <div className="px-4 py-3 border-t border-slate-700 bg-slate-800/80 rounded-b-xl flex flex-col gap-3">
              
              {/* Progress Dots */}
              {!exportError && !generatedHtml && (
                <div className="flex justify-between items-center text-[11px] text-slate-400">
                    <div className="flex gap-1.5 items-center">
                    <span className="mr-2">Progress:</span>
                    {Array.from({length: Math.min(totalCards || 3, 15)}).map((_, i) => (
                        <div 
                        key={i} 
                        className={`w-1.5 h-1.5 rounded-full transition-colors duration-300 ${
                            completedCards.includes(i) ? 'bg-emerald-500' : 
                            (currentCardIndex === i && isExporting ? 'bg-indigo-500 animate-pulse' : 'bg-slate-700')
                        }`} 
                        />
                    ))}
                    {(totalCards > 15) && <span>...</span>}
                    </div>
                    <span>{Math.round((completedCards.length / (totalCards || 1)) * 100)}%</span>
                </div>
              )}

              {/* Manual Actions (Shown when done or if error allows retry logic - though here just done) */}
              {generatedHtml && !isExporting && (
                  <button
                    onClick={() => generatedHtml && performCopy(generatedHtml)}
                    className="w-full py-2 bg-indigo-600 hover:bg-indigo-500 text-white text-sm font-medium rounded-lg transition shadow-lg shadow-indigo-900/20 flex items-center justify-center gap-2"
                  >
                    {copiedType === 'html' ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                    {copiedType === 'html' ? "Copied to Clipboard!" : "Copy Result to Clipboard"}
                  </button>
              )}
          </div>
        </div>,
        document.body
      )}
    </>
  );
};
